### ISSUE TITLE
OSError: 2

### ISSUE THREAD

**Issue by yushaye** [drcoms/client-micropy#1]
Traceback (most recent call last):
  File "./drcom.py", line 4, in <module>
  File "/tmp/libs/os.py", line 22, in <module>
OSError: 2

**Comment by mchome** [comment]
在dev分支再试下

**Comment by yushaye** [comment]
![6 1 j k 31_irt1 _f5 0](https://cloud.githubusercontent.com/assets/17774848/13733054/85bd636a-e9c8-11e5-8bb3-5bc7e63a542e.jpg)
在dev文件夹下还是这样。。。

**Comment by mchome** [comment]
不，把之前的都删掉，直接用dev分支的

**Comment by yushaye** [comment]
dev的还是oserror

**Comment by yushaye** [comment]
d版的不知道要装些什么py包，现在的openwrt里没有py-mini了，我装了python-base,py-light-py-logging,py-openssl后import d版的所有包都不会弹错，但是就是运行不了，一直跳challenge timeout retrying，我把d版的放到ubuntu里面就能正常登陆。。。micropython版的也用不了。

**Comment by mchome** [comment]
建议你装个tcpdump抓包看一下，有没有把数据包发出去，另外OSError在第几行错了

**Comment by yushaye** [comment]
换了个16m flash的路由器装了全套py平台后能用了，谢谢你耐心的解答！
